### ISSUE TITLE
Failed to apply transformation

### ISSUE THREAD

**Issue by OndrejZamazal** [Onto-DESIDE-VSE/patomat2#26]
Input: cmt.owl and CAT1ntp-tp-lite.json. When I select one or more instances to transform, it returns error "Failed to apply transformation".

https://oaei.ontologymatching.org/2024/conference/data/cmt.owl
https://github.com/Onto-DESIDE-VSE/TransformationPatterns/blob/main/submissions/CAT1ntp-tp-lite.json

**Comment by ledsoft** [comment]
Was just a problem of the bottom button not calling the transformation correctly.
