### ISSUE TITLE
Allow blank nodes with a disjunction of classes in the domain to be among matching bindings and ready for selection for transformation

### ISSUE THREAD

**Issue by OndrejZamazal** [Onto-DESIDE-VSE/patomat2#53]
As a user, I want to have the option to see classes from disjunction from the domain among matching bindings and allow classes from disjunction to participate in the transformation.

For example
TP: https://github.com/Onto-DESIDE-VSE/TransformationPatterns/blob/main/submissions/CAT1ntp-tp-lite2x.json
Ontology: https://oaei.ontologymatching.org/2024/conference/data/cmt.owl

Currently,  the following matching bindings of blank nodes are suppressed:
"A","p","B","C"
"b0","http://cmt#markConflictOfInterest","http://cmt#Paper","http://cmt#PaperFullVersion"
"b0","http://cmt#markConflictOfInterest","http://cmt#Paper","http://cmt#PaperAbstract"

Where,  for example, b0 is "Author or Chairman or Reviewer."

Instead, these blank nodes should be displayed, for example:
"A","p","B","C"
"Author or Chairman or Reviewer","http://cmt#markConflictOfInterest","http://cmt#Paper","http://cmt#PaperFullVersion"
"Author or Chairman or Reviewer","http://cmt#markConflictOfInterest","http://cmt#Paper","http://cmt#PaperAbstract"

Then, by default, the Author is selected for transformation, but I want an option to select each to be included in further transformation.

**Comment by OndrejZamazal** [comment]
It meant there would be no union in transformation anymore (only in the detection phase). The transformation would be considered separately for each selected entity from the union. Similarly, the label would be generated for each selected entity separately.

Deleting is difficult in this case. Would it be possible not to support deletion in cases where blank nodes were present?

**Comment by ledsoft** [comment]
So we can basically treat the union as multiple instances of the pattern? We can skip deletion, that's no problem.

**Comment by OndrejZamazal** [comment]
Yes, it was the initial idea, but maybe not directly articulated :)
